FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY bot ./bot

COPY calendarapp ./calendarapp

CMD ["python", "-m", "bot.bot"]