# Generated by Django 5.2.3 on 2025-06-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_alter_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user_count', models.PositiveIntegerField()),
                ('event_count', models.PositiveIntegerField()),
                ('edited_events', models.PositiveIntegerField()),
                ('cancelled_events', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Статистика бота',
                'verbose_name_plural': 'Статистика бота',
                'db_table': 'bot_statistics',
            },
        ),
    ]
