# Generated by Django 5.2.3 on 2025-06-13 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_botstatistics_user_user_events_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendarapp.user'),
        ),
        migrations.AlterUniqueTogether(
            name='botstatistics',
            unique_together={('user', 'date')},
        ),
    ]
